// Generated by `wit-bindgen` 0.32.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace WasiHttpWorld.wit.exports.wasi.http.v0_2_0;

internal interface IIncomingHandler {
    static abstract void Handle(global::WasiHttpWorld.wit.imports.wasi.http.v0_2_0.ITypes.IncomingRequest request, global::WasiHttpWorld.wit.imports.wasi.http.v0_2_0.ITypes.ResponseOutparam responseOut);

}
