<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\DefaultBrowserSample.targets" />
  <PropertyGroup>
    <EnableDiagnostics>false</EnableDiagnostics>
    <MetricsSupport>false</MetricsSupport>
    <EventSourceSupport>false</EventSourceSupport>
    <CompressionEnabled>false</CompressionEnabled>
    <StackTraceSupport>false</StackTraceSupport>
    <DebugSymbols>false</DebugSymbols>
    <StackTraceLineNumberSupport>false</StackTraceLineNumberSupport>
    
    <EnableAggressiveTrimming>true</EnableAggressiveTrimming>
    <PublishTrimmed>true</PublishTrimmed>
    <_ExtraTrimmerArgs>$(_ExtraTrimmerArgs) --dump-dependencies</_ExtraTrimmerArgs>
  </PropertyGroup>
</Project>
