// Generated by `wit-bindgen` 0.32.0. DO NOT EDIT!
// <auto-generated />
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Collections;
using System.Runtime.InteropServices;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace WasiHttpWorld.wit.exports.wasi.http.v0_2_0
{
    internal static class IncomingHandlerInterop {

        [UnmanagedCallersOnly(EntryPoint = "wasi:http/incoming-handler@0.2.0#handle")]
        internal static unsafe void wasmExportHandle(int p0, int p1) {

            var resource = new global::WasiHttpWorld.wit.imports.wasi.http.v0_2_0.ITypes.IncomingRequest(new global::WasiHttpWorld.wit.imports.wasi.http.v0_2_0.ITypes.IncomingRequest.THandle(p0));
            var resource0 = new global::WasiHttpWorld.wit.imports.wasi.http.v0_2_0.ITypes.ResponseOutparam(new global::WasiHttpWorld.wit.imports.wasi.http.v0_2_0.ITypes.ResponseOutparam.THandle(p1));
            IncomingHandlerImpl.Handle((resource), (resource0));

        }

    }
}
